// <auto-generated />
using Capital.Funds.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capital.Funds.Migrations
{
    [DbContext(typeof(ApplicationDb))]
    [Migration("20231215211826_FirstOne")]
    partial class FirstOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Capital.Funds.Models.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "7af918f9-02cd-489a-9ac2-2d79c4b2ae85",
                            Email = "admin@admin.com",
                            Gender = 1,
                            Name = "Capital Fund",
                            Password = "0VdQ3re+oqkMGfBdBGkV4Xg6goD4KjmXiFjLTOdYgGE=",
                            Role = "admin",
                            Salt = "5NLVzEUbIkM21/pa1qtYvo4YQ6oQ8TFXp4V3I/g89H8="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
