// <auto-generated />
using Capital.Funds.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capital.Funds.Migrations
{
    [DbContext(typeof(ApplicationDb))]
    [Migration("20231215223538_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Capital.Funds.Models.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isEmailVerified")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "0f5bf085-ee73-442b-b62d-dcc16a28cb23",
                            Email = "admin@admin.com",
                            Gender = 1,
                            IsActive = false,
                            Name = "Capital Fund",
                            OTP = "112233",
                            Password = "CmARNJlN4uhOZh/CZo3KMdRzENjHKjJBGcBtS9eYEQs=",
                            Role = "admin",
                            Salt = "J4slEC+WDFMyqtnTqMjDItg5BQqRpCB/Qql1qUsM12g=",
                            isEmailVerified = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
